spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#    application:
#        name: ${SPRING_APPLICATION_NAME:Demo}
    data:
        mongodb:
            uri: mongodb+srv://chuaii12138:0131chychy@cluster0.irxke6g.mongodb.net/club
#    banner:
#        charset: UTF-8

server:
    servlet:
        context-path: /
#        encoding:
#            charset: UTF-8
#            enabled: true
#            force: true
    port: 12138
#    tomcat:
#        uri-encoding: UTF-8
#    ssl:
#        enabled: false
